# config.yaml
cookie:
  expiry_days: 30       # Thời gian hết hạn của cookie (ngày)
  key: "motkhoadainam"  # Khóa mã hóa cho cookie (PHẢI DÀI VÀ NGẪU NHIÊN)
  name: "app_cookie"    # Tên cookie
credentials:
  usernames:
    admin: # Tên đăng nhập 1
      email: admin@example.com
      name: Quản trị viên # Tên hiển thị
      password: $2b$12$aWbCeIBCqgf7.nWyFIozNuLSXfT37S.sIQXGjnhfDf9Az006h3Joe # Mật khẩu đã mã hóa vietthanh
    user1: # Tên đăng nhập 2
      email: user1@example.com
      name: Người dùng thường
      password: $2b$12$0UAYTUfWrzp0yMQaxy8WQ.mR6z0N3BuyAeqWy28LovE5c9z9Iz1S6 # Mật khẩu mã hóa password